In [ ]:
#INTRODUCTION AU SCIKIT_LEARN
   Python n’est pas un langage bon juste dans l’ingénierie des données. En dehors des bibliothèques comme Panda,
ou NumPy, il intègre également une bibliothèque incontournable pour la data science : Scikit-Learn. 

    Scikit-Learn est une bibliothèque Python spécialisée dans dans les travaux de Data Science.C’est une bibliothèque
facilement accessible, et puissante,  qui s’intègre naturellement dans l’écosystème plus large des outils de science
des données basés sur Python.



In [ ]:

#Définition de Scikit-Learn

    Scikit-learn, encore appelé sklearn, est la bibliothèque la plus puissante et la plus robuste pour le machine 
learning en Python. Elle fournit une sélection d’outils efficaces pour l’apprentissage automatique et la
modélisation statistique, notamment la classification, la régression et le clustering via une interface cohérente
en Python. Cette bibliothèque, qui est en grande partie écrite en Python, s’appuie sur NumPy, SciPy et Matplotlib.


In [ ]:
  #Historique
Scikit-learn a été initialement développé par David Cournapeau dans le cadre du projet Google summer of code en 2007. 
Plus tard, Matthieu Brucher a rejoint le projet et a commencé à l’utiliser dans le cadre de son travail de thèse.
En 2010, l’INRIA s’est impliqué et la première version publique (v0.1 beta) a été publiée fin janvier 2010.

Le projet compte maintenant plus de 30 contributeurs actifs et a bénéficié du soutien financier de l’INRIA,
de Google, de Tinyclues et de la Python Software Foundation.


 
   #Pourquoi utiliser Scikit-Learn 
    
    Les principales raisons qui poussent à utiliser Scikit-Learn sont : 
        Scikit-learn possède une licence BSD ; par conséquent, il existe une restriction minimale
            sur l’utilisation et la distribution du logiciel, ce qui le rend libre d’utilisation pour tous; propose
            une documentation détaillée. De plus, Scikit-Learn est facile à utiliser et s'utilise de facon
            intensive dans l'industrie

  
     #INSTALLATION de Scikit-Learn
    
    La façon la plus simple d’installer non seulement Scikit-learn, mais aussi Python et ses 
      paquets les plus populaires (IPython, SciPy NumPy, Matplotlib) est d’utiliser Anaconda,
      une distribution Python multiplateforme (Linux, macOS, Windows) pour l’analyse de données 
      et le calcul scientifique.

         Commande d'installation : conda install -c anaconda scikit-learn


In [ ]:
#Charger et sauvegarder des données

   À partir de fichiers qui présentent des formats simples, les données peuvent être
    lues en utilisant la fonction loadtxt de NumPy. La fonction genfromtxt de NumPy donne 
    une flexibilité supplémentaire mais peut ralentir la lecture pour des fichiers de taille plus importante.

Le package sklearn.dataset inclut des fonctions supplémentaires de lecture, de génération de données, 
ainsi que plusieurs ensemble de données qu’il n’est plus nécessaire de télécharger. Vous pouvez examiner
les fonctions proposées sur http://scikit-learn.org/stable/datasets/. Les données sont représentées en 
    général par un tuple (X, y), où X est un tableau bidimensionnel NumPy de n_samples x n_features contenant
    les valeurs des variables d’entrée et y un tableau unidimensionnel NumPy de longueur n_samples contenant 
    les résultats désirés.

Il est ainsi possible de lire directement des données en format SVMlight / LibSVM, dans lequel chaque observation 
        correspond à une ligne de fichier sous la forme suivante :
        <label> <feature-id>:<feature-value> <feature-id>:<feature-value> ..., où 
                <label> est le résultat désiré pour cette observation (par ex. l’étiquette de classe), 
                et chaque paire <feature-id>:<feature-value> donne un index où la valeur est non nulle et
                la valeur associée. Ce format est particulièrement utile pour des données creuses
                (de nombreuses valeurs nulles, qui ainsi ne sont pas stockées) mais est parfois 
                employé comme format par défaut même lorsque les valeurs ne sont pas nulles. 
    L’utilisation est décrite sur :
    https://scikit-learn.org/stable/datasets/loading_other_datasets.html#datasets-in-svmlight-libsvm-format.
    

In [ ]:
#Prétraiter des données

Plusieurs fonctionnalités de pré-traitement des données sont disponibles dans le package 
 sklearn.preprocessing : outils pour centrer le nuage des observations (rendre la moyenne de chaque
  variable égale à 0), pour centrer et réduire les variables (rendre la moyenne de chaque variable égale à 0,
  puis rendre la variance de chaque variable égale à 1), pour normer les observations (rendre la norme de chaque 
  observation égale à 1), pour (re)coder des variables (par exemple, codage d’une variable nominale à m modalités 
  par m variables binaires, comme nous l’avons vu en cours), transformations ad-hoc (par exemple, application
 de transformations logarithmiques à certaines variables). 
    Par exemple, pour centrer et réduire les variables correspondant aux deux colonnes de geyser :

from sklearn import preprocessing
geyser = np.loadtxt('geyser.txt')
geyser[:5,:]

On créé un objet Scaler que l’on applique sur les données geyser :

geyserCR = preprocessing.scale(geyser)
geyserCR[:5,:]

On peut ensuite vérifier que la moyenne des données normalisées est bien nulle et l’écart-type unitaire :

print(geyser.mean(axis=0))
# array([  3.48778309,  70.89705882])
print(geyserCR.mean(axis=0))
# array([  4.48579082e-16,   4.27048103e-16])
print(geyser.std(axis=0))
# array([  1.13927121,  13.56996002])
print(geyserCR.std(axis=0))
# array([ 1.,  1.])



In [ ]:

#Générer des données

Le package sklearn.dataset comprend aussi quelques outils de génération de données, adaptés à différents
types de problèmes : classification automatique, classement (discrimination) à deux ou plusieurs classes, 
régression, apprentissage de manifolds. 

#Construire des modèles

Dans Scikit-learn, un estimator est un objet qui implémente la méthode fit(X, y) pour estimer un modèle 
et predict(T) afin d’utiliser ce modèle pour prendre des décisions (faire des prédictions).
Des exemples de telles classes : sklearn.svm.SVC, sklearn.discriminant_analysis.LinearDiscriminantAnalysis.
    
#Charger et sauvegarder des modèles

Comme nous l’avons vu dans la séance introductive, pickle (import pickle) permet de sérialiser 
(pour enregistrer dans un fichier ou écrire dans un string) et de désérialiser (pour lire depuis 
 un fichier ou depuis un string) un objet quelconque, donc également un modèle.
